{
 "title": "Application metrics",
 "description": "Application metrics",
 "time": { "from": "now-15m", "to": "now" },
 "refresh": "5s",
 "panels": [
  { "title": "Main", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "Redis cache hit",
   "type": "singlestat",
   "gridPos": { "h": 8, "w": 5, "x": 0, "y": 1 },
   "format": "none",
   "valueName": "avg",
   "targets": [
    { "expr": "redis_cache_hit_counter" }
   ]
  },
  {
   "title": "Median Response Time",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 6, "y": 1 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "histogram_quantile(0.5, sum(rate(http_request_duration_ms_bucket[1m])) by (le, service, route, method))"
    }
   ]
  },
  {
   "title": "Apdex",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 6, "y": 9 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "(\n  sum(rate(http_request_duration_ms_bucket{le=\"100\"}[1m])) by (service)\n+\n  sum(rate(http_request_duration_ms_bucket{le=\"300\"}[1m])) by (service)\n) / 2 / sum(rate(http_request_duration_ms_count[1m])) by (service)"
    }
   ]
  },
  {
   "title": "Memory Usage",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 6, "y": 17 },
   "fieldConfig": { "defaults": { "unit": "decmbytes" } },
   "yaxes": [
    { "format": "decmbytes" }
   ],
   "targets": [
    {
     "expr": "avg(nodejs_external_memory_bytes / 1024 / 1024) by (service)"
    }
   ]
  }
 ]
}